tap "delphinus/sfmono-square"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"

# Homebrew

brew "bitwarden-cli"
brew "carthage"
brew "fastlane"
brew "ffmpeg"
# brew "gcc"
brew "gh"
brew "git"
# brew "gnuplot"
brew "graphviz"
brew "hugo"
# brew "imagemagic"
brew "mas"
brew "mint"
# brew "nkf"
brew "peco"
brew "rbenv"
brew "rbenv-communal-gems"
brew "reattach-to-user-namespace" # fix tmux [exited]
brew "ruby-build"
brew "sfmono-square"
brew "skhd"
brew "spacebar"
brew "swiftlint"
brew "tmux"
brew "vim"
brew "xcodegen"
brew "yabai"

# Homebrew cask

# cask "adobe-acrobat-reader"
# cask "alacritty"
cask "alfred"
# cask "aquaterm"
# cask "atom"
# cask "background-music"
cask "bettertouchtool"
# cask "ccleaner"
cask "charles"
# cask "cheatsheet"
# cask "clickup"
# cask "dash"
cask "discord"
cask "docker"
# cask "dropbox"
cask "emacs"
# cask "firefox"
cask "font-mplus"
cask "font-source-han-code-jp"
cask "fork"
# cask "gimp"
# cask "google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "hammerspoon"
# cask "inkscape"
cask "iterm2"
cask "oracle-jdk"
cask "karabiner-elements"
# cask "macs-fan-control"
# cask "mactex"
cask "meetingbar"
# cask "mendeley"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
# cask "miro"
cask "mos"
cask "notion"
cask "obs"
cask "obs-virtualcam"
# cask "obsidian"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qmk-toolbox"
cask "quicklook-csv"
cask "quicklook-json"
cask "screen"
# cask "scroll-reverser"
cask "sf-symbols"
# cask "skype"
# cask "sourcetree"
# cask "spotify"
# cask "station"
# cask "steermouse"
# cask "suspicious-package"
# cask "taskade"
cask "the-unarchiver"
# cask "ticktick"
# cask "toggl"
# cask "typora"
cask "visual-studio-code"
cask "vlc"
cask "webpquicklook"
# cask "xquartz"
cask "zeplin"
cask "zoom"

# mas

# mas "BetterSnapTool", id:417375580
mas "CommentScreen", id:1450950860
mas "cotEditor", id: 1024640650
mas "Dropover", id: 1355679052
# mas "Kindle", id: 405399194
mas "LINE", id: 539883307
# mas "Manico", id: 724472954
# mas "Mathpix", id: 1349670778
# mas "Nozbe", id: 508957583
mas "Slack", id: 803453959
# mas "ToyViewer", id: 414298354
mas "Xcode", id: 497799835

